name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-test:
     runs-on: ubuntu-latest
     name: "Unit Test"
     steps:
       - uses: actions/checkout@v2
       - name: Setup go
         uses: actions/setup-go@v1
         with:
           go-version: "1.20"
       - name: Run Unit Test
         run: |
           make test